// Verifies design/diagrams/system-topology.drawio is in sync with its sources
// (system.yaml + design/diagrams/topology-layout.yaml). If someone edits a
// source file without regenerating, this test fails with instructions.
//
// Fix a failure with:
//   npm run diagram
// then commit the regenerated drawio file.

const { test } = require('node:test');
const assert = require('node:assert');
const fs = require('node:fs');
const path = require('node:path');

const { generateTopology } = require('../design/diagrams/generate-topology.js');

const DRAWIO_PATH = path.resolve(
  __dirname,
  '..',
  'design',
  'diagrams',
  'system-topology.drawio',
);

test('system-topology.drawio is up-to-date with generator sources', () => {
  const { xml: expected } = generateTopology({ silent: true });
  const actual = fs.readFileSync(DRAWIO_PATH, 'utf8');

  if (actual !== expected) {
    // Show the first differing line to make diagnosis easy.
    const expectedLines = expected.split('\n');
    const actualLines = actual.split('\n');
    let firstDiffLine = -1;
    for (let i = 0; i < Math.max(expectedLines.length, actualLines.length); i++) {
      if (expectedLines[i] !== actualLines[i]) {
        firstDiffLine = i + 1;
        break;
      }
    }
    assert.fail(
      'design/diagrams/system-topology.drawio is out of date.\n\n' +
        `  First differing line: ${firstDiffLine}\n` +
        `  Committed bytes: ${actual.length}\n` +
        `  Generated bytes: ${expected.length}\n\n` +
        'Regenerate and commit:\n' +
        '  npm run diagram\n' +
        '  git add design/diagrams/system-topology.drawio\n',
    );
  }
});

const PLAYGROUND_DRAWIO_PATH = path.resolve(
  __dirname,
  '..',
  'playground',
  'assets',
  'system-topology.drawio',
);

test('playground/assets/system-topology.drawio is up-to-date (playground theme)', () => {
  const { xml: expected } = generateTopology({ theme: 'playground', silent: true });
  const actual = fs.readFileSync(PLAYGROUND_DRAWIO_PATH, 'utf8');

  if (actual !== expected) {
    const expectedLines = expected.split('\n');
    const actualLines = actual.split('\n');
    let firstDiffLine = -1;
    for (let i = 0; i < Math.max(expectedLines.length, actualLines.length); i++) {
      if (expectedLines[i] !== actualLines[i]) {
        firstDiffLine = i + 1;
        break;
      }
    }
    assert.fail(
      'playground/assets/system-topology.drawio is out of date.\n\n' +
        `  First differing line: ${firstDiffLine}\n` +
        `  Committed bytes: ${actual.length}\n` +
        `  Generated bytes: ${expected.length}\n\n` +
        'Regenerate and commit:\n' +
        '  npm run topology-drawio-playground\n' +
        '  npm run topology-svg-playground\n' +
        '  git add playground/assets/system-topology.drawio playground/assets/system-topology.svg\n',
    );
  }
});
