#!/bin/sh
# Generate OpenVPN server config with static key for UniFi site-to-site VPN.
#
# Usage:
#   ./setup.sh [options]
#
# Options:
#   --server-address    Cloud server IP or hostname (default: greenhouse.madekivi.fi)
#   --server-tunnel-ip  Server tunnel endpoint (default: 10.10.10.1)
#   --client-tunnel-ip  Client tunnel endpoint (default: 10.10.10.2)
#   --remote-network    Client-side LAN subnet (default: 192.168.1.0/24)
#   --port              OpenVPN port (default: 1194)
#   --output            Output config file path (default: ./openvpn.conf)
#
# If openvpn is not installed locally, uses Docker (alpine) to generate the key.

set -e

# Defaults
SERVER_IP="greenhouse.madekivi.fi"
SERVER_TUNNEL_IP="10.10.10.1"
CLIENT_TUNNEL_IP="10.10.10.2"
REMOTE_NETWORK="192.168.1.0/24"
PORT="1194"
OUTPUT="./openvpn.conf"

# Parse arguments
while [ $# -gt 0 ]; do
  case "$1" in
    --server-address)  SERVER_IP="$2"; shift 2 ;;
    --server-tunnel-ip) SERVER_TUNNEL_IP="$2"; shift 2 ;;
    --client-tunnel-ip) CLIENT_TUNNEL_IP="$2"; shift 2 ;;
    --remote-network)  REMOTE_NETWORK="$2"; shift 2 ;;
    --port)            PORT="$2"; shift 2 ;;
    --output)          OUTPUT="$2"; shift 2 ;;
    -h|--help)
      sed -n '2,/^$/p' "$0" | sed 's/^# \?//'
      exit 0
      ;;
    *)
      echo "Unknown option: $1" >&2
      exit 1
      ;;
  esac
done

# Split remote network into address and netmask
NETWORK_ADDR=$(echo "$REMOTE_NETWORK" | cut -d/ -f1)
CIDR=$(echo "$REMOTE_NETWORK" | cut -d/ -f2)

# Convert CIDR to dotted netmask
cidr_to_netmask() {
  local cidr=$1
  local mask=""
  local full_octets=$((cidr / 8))
  local partial_bits=$((cidr % 8))
  local i=0

  while [ $i -lt 4 ]; do
    if [ $i -lt "$full_octets" ]; then
      mask="${mask}255"
    elif [ $i -eq "$full_octets" ]; then
      mask="${mask}$((256 - (1 << (8 - partial_bits))))"
    else
      mask="${mask}0"
    fi
    [ $i -lt 3 ] && mask="${mask}."
    i=$((i + 1))
  done
  echo "$mask"
}

NETMASK=$(cidr_to_netmask "$CIDR")

# Generate static key
echo "Generating OpenVPN static key..."
TMPKEY=$(mktemp)

if command -v openvpn >/dev/null 2>&1; then
  openvpn --genkey secret "$TMPKEY" 2>/dev/null
else
  echo "openvpn not found locally, using Docker..."
  docker run --rm alpine:3.21 sh -c "apk add --no-cache openvpn >/dev/null 2>&1 && openvpn --genkey secret /dev/stdout 2>/dev/null" > "$TMPKEY"
fi

# Extract key content (lines between BEGIN/END markers, inclusive)
KEY_CONTENT=$(cat "$TMPKEY")

# Build the config file
cat > "$OUTPUT" <<CONF
# OpenVPN server configuration for UpCloud server (site-to-site with UniFi gateway)
# Generated by setup.sh on $(date -Iseconds)
# Static key (PSK) mode — compatible with UniFi site-to-site VPN

dev tun
proto udp
port $PORT

# Tunnel endpoint IPs: server (cloud) = local, client (UniFi) = remote
ifconfig $SERVER_TUNNEL_IP $CLIENT_TUNNEL_IP

# Route to UniFi's LAN (the home network with Shelly devices)
route $NETWORK_ADDR $NETMASK

# Keepalive: ping every 15s, restart after 45s of silence
ping 15
ping-restart 45
ping-timer-rem

# Encryption — must match UniFi cipher setting
cipher AES-256-CBC

# Persist across restarts
persist-tun
persist-key

# Logging
verb 3

# Pre-shared static key (embedded inline)
<secret>
$KEY_CONTENT
</secret>
CONF

rm -f "$TMPKEY"

echo ""
echo "=== OpenVPN server config written to: $OUTPUT ==="
echo ""
echo "=== UniFi UI Configuration ==="
echo "Settings → VPN → Create New VPN → OpenVPN"
echo ""
echo "  Name:                  greenhouse-cloud"
echo "  Pre-Shared Key:        (paste the key block below)"
echo "  Local Tunnel IP:       $CLIENT_TUNNEL_IP"
echo "  Local Port:            $PORT"
echo "  Cipher:                AES-256-CBC"
echo "  Remote Networks:       $SERVER_TUNNEL_IP/32"
echo "  Remote IP Address:     $SERVER_IP"
echo "  Remote Tunnel IP:      $SERVER_TUNNEL_IP"
echo "  Port:                  $PORT"
echo "  MTU:                   Auto"
echo "  MSS:                   Auto"
echo ""
echo "=== Pre-Shared Key (paste into UniFi) ==="
echo ""
# Extract just the hex lines (no headers/comments) for UniFi
grep -v '^#' "$OUTPUT" | sed -n '/<secret>/,/<\/secret>/p' | grep -v '<secret>' | grep -v '</secret>' | tr -d '\n'
echo ""
echo ""
echo "=== Next Steps ==="
echo "1. Copy $OUTPUT to /opt/app/openvpn.conf on the server"
echo "2. Set enable_vpn = true in Terraform and run: terraform apply"
echo "3. Enter the values above in UniFi UI"
echo "4. The deployer will start the OpenVPN container on next run (~5 min)"
