apiVersion: v1
kind: Service
metadata:
  name: app-preview-pr-${PR_NUMBER}
  labels:
    preview-pr: "${PR_NUMBER}"
    purpose: preview
  annotations:
    preview.greenhouse/expires-at: "${EXPIRES_AT}"
spec:
  type: ClusterIP
  selector:
    preview-pr: "${PR_NUMBER}"
  ports:
    - name: http
      port: 3000
      targetPort: 3000
